---

- name: Install Podman and setup rootless Podman
  import_tasks: setup.yml

- name: Check if systemd service file exists already
  tags: [ configure_container_service ]
  stat:
    path: "{{ service_files_dir }}/{{ service_name }}"
  register: service_file_before_template

- name: Deploy containers and setup systemd unit files for pods and containers
  import_tasks: container.yml

- name: Configure firewall
  import_tasks: firewall.yml

- name: Stop then remove containers and pods systemd unit files
  import_tasks: removal.yml







  




  
