---
- name: Ensure podman is installed
  become: yes
  tags: [ install_podman ]
  package:
    name: podman
    state: present
  when: not skip_podman_install

- name: Get details about {{ container_run_as_user }} needed for rootless containers
  tags: [ container_run_as_user ]
  when: container_run_as_user != "root"
  block:
    - name: Get user information
      user:
        name: "{{ container_run_as_user }}"
      check_mode: true
      register: user_info

    - name: Get systemd dir if user is not root
      set_fact:
        service_files_dir: "{{ user_info.home }}/.config/systemd/user"
        systemd_scope: user
      changed_when: false

    - name: Ensure systemd files directory exists if user not root
      file:
        path: "{{ service_files_dir }}"
        state: directory
        owner: "{{ container_run_as_user }}"
        group: "{{ container_run_as_group }}"
        mode: '0755'

- name: Find the user id for container user {{ container_run_as_user }}
  tags: [ setup ]
  command: "id -u {{ container_run_as_user }}"
  register: container_run_as_uid
  check_mode: false  # Run even in check mode, to avoid fail with --check.
  changed_when: false

- name: Declare systemd runtime dir
  tags: [ setup ]
  set_fact:
    xdg_runtime_dir: "/run/user/{{ container_run_as_uid.stdout }}"
  changed_when: false

- name: Declare systemd_scope, service_files_dir and xdg_runtime_dir
  tags: [ setup ]
  set_fact:
    systemd_scope: system
    service_files_dir: '/etc/systemd/system'
    xdg_runtime_dir: "/run/user/{{ container_run_as_uid.stdout }}"
  when: container_run_as_user == "root"
  changed_when: false